name: moonblink
description: MoonBlink Universe's app

version: 2.0.0+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # State Management
  provider: ^4.0.4
  path_provider: ^1.6.11
  #Base Component
  platform_device_id: ^0.1.1
  device_info: ^0.4.2+4
  package_info: ^0.4.1
  clipboard: ^0.1.2+8
  #Base UI
  shimmer: ^1.1.1
  flutter_holo_date_picker: ^0.1.5
  datetime_picker_formfield: ^1.0.0
  cached_network_image: ^2.0+1
  flutter_blurhash: ^0.5.0
  oktoast: ^2.3.2
  pull_to_refresh: ^1.6.0
  share: ^0.6.4+3
  flutter_local_notifications: ^1.4.4+1 # Android API 16+ (4.1+, the minimum version supported by Flutter). Uses the NotificationCompat APIs so it can be run older Android devices # iOS 8.0+ (the minimum version supported by Flutter). Supports the old and new iOS notification APIs (the User Notifications Framework introduced in iOS 10 but will use the UILocalNotification APIs for devices predating iOS 10)
  smooth_star_rating: ^1.1.1
  flutter_ffmpeg: 0.2.10
  video_thumbnail: ^0.2.2
  # fancy_bottom_navigation: ^0.3.2
  # Data
  photo_view: ^0.9.2
  audioplayers: ^0.15.1
  flutter_audio_recorder: ^0.5.5
  dio: ^3.0.9
  shared_preferences: ^0.5.6+3
  socket_io_client: ^0.9.4
  scoped_model: ^1.0.1
  url_launcher: ^5.5.0
  #voice call
  agora_rtc_engine: 1.0.13 #need to edit at android and ios
  permission_handler: ^5.0.1
  #camera
  camera: ^0.5.8+2 #need to edit at ios,andorid require 21 sdk version
  # local storage
  image_picker: ^0.6.7+11 #need to edit at android and ios
  localstorage: ^3.0.2+5
  flutter_cache_manager: ^1.4.1
  story_view: ^0.12.3
  vibration: ^1.4.0
  # signIn helper
  google_sign_in: ^4.5.1 #complete for both
  flutter_facebook_login: ^3.0.0 #complete for both
  # FCM
  firebase_messaging: ^6.0.16
  # This is a simple Service Locator for Dart and Flutter projects with some additional goodies highly inspired by Splat. It can be used instead of InheritedWidget or Provider to access objects e.g. from your UI.
  get_it: ^4.0.2
  in_app_purchase: ^0.3.4+5
  # image_compressing
  flutter_image_compress: ^0.7.0
  # video_player
  video_player: ^0.10.11+2
  common_utils: ^1.2.1
  # DateFormat
  timeago: ^2.0.26
  # Bloc Pattern
  flutter_bloc: ^6.0.1
  # RxDart
  rxdart: ^0.24.1
  # Simplify Equality Comparisons
  equatable: ^1.2.2
  flutter_swiper: ^1.1.6
  # ADs
  firebase_admob: ^0.9.3+4
  # native Ads
  flutter_native_admob: ^2.1.0
  # Firebase Auth - // Phone OTP
  firebase_auth: ^0.16.1
  # loading image from local -- new libraries
  photo_manager: ^0.5.7
  # Apple Sign in - android, ios and mac support
  sign_in_with_apple: ^2.5.2
  # Apple Sign in 2 - only iOS support
  apple_sign_in: ^0.1.0
  #encrypt
  encrypt: ^4.0.2
  #crop, compresss, resize image
  image_cropper: ^1.3.0
  # swipe list tile to show more options
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.0
  font_awesome_flutter: ^8.8.1 #The Font Awesome Icon pack available as set of Flutter Icons.
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # json_serializable: ^3.3.0
  # build_runner: ^1.9.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/mainTab/
    - assets/icons/status/
    - assets/images/
    - assets/logos/
    - images/0.jpg
    - images/1.jpeg
    - images/2.jpeg
    - images/3.jpeg
    - images/4.jpeg
    - images/5.jpeg


  fonts:
    # - family: iconfont
    - family: appIconFonts
      fonts:
        # - asset: assets/fonts/alihomeiconfont.ttf
        - asset: assets/fonts/iconfont.ttf

flutter_intl:
  enabled: true
  class_name: G 