name: moonblink
description: MoonBlink Universe's app
publish_to: 'none'

version: 3.1.0+49

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.0 #The Font Awesome Icon pack available as set of Flutter Icons.
  # flutter_snake_navigationbar: ^0.4.2
  # convex_bottom_bar: ^2.6.0
  # State Management
  provider: ^4.3.2+2
  path_provider: ^1.6.21
  #Base Component
  platform_device_id: ^0.1.1
  device_info: ^0.4.2+9
  package_info: ^0.4.3
  clipboard: ^0.1.2+8
  grouped_list: ^3.5.0
  selectable_autolink_text: ^1.3.5
  #Base UI
  shimmer: ^1.1.2
  flutter_holo_date_picker: ^0.2.1
  datetime_picker_formfield: ^1.0.0
  cached_network_image: ^2.5.0
  oktoast: ^2.3.2
  pull_to_refresh: ^1.6.2
  share: ^0.6.5+3
  flutter_local_notifications: ^3.0.1+4 # Android API 16+ (4.1+, the minimum version supported by Flutter). Uses the NotificationCompat APIs so it can be run older Android devices # iOS 8.0+ (the minimum version supported by Flutter). Supports the old and new iOS notification APIs (the User Notifications Framework introduced in iOS 10 but will use the UILocalNotification APIs for devices predating iOS 10)
  smooth_star_rating: ^1.1.1
  #TODO: IChange here also Change At Stories Page too
  flutter_ffmpeg: 0.3.0
  video_thumbnail: ^0.2.2
  # Data
  photo_view: ^0.10.2
  audioplayers: ^0.16.1
  dio: ^3.0.10
  flutter_plugin_record: ^0.3.4
  shared_preferences: ^0.5.12+2
  socket_io_client: ^0.9.11
  scoped_model: ^1.1.0
  url_launcher: ^5.7.7
  #voice call
  # agora_rtc_engine: ^3.1.3
  agora_rtc_engine: ^3.2.1
  # agora_rtc_engine: 1.0.13 #need to edit at android and ios
  permission_handler: ^5.0.1+1
  #camera
  camera: ^0.5.8+11 #need to edit at ios,andorid require 21 sdk version
  # local storage
  image_picker: ^0.6.7+12 #need to edit at android and ios
  localstorage: ^3.0.3+6
  #Can't change here cuz storyview no update
  flutter_cache_manager: ^2.0.0
  story_view: ^0.12.6
  vibration: ^1.7.1
  # signIn helper
  google_sign_in: ^4.5.5 #complete for both
  flutter_facebook_login: ^3.0.0 #complete for both
  # FCM
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.2
  # This is a simple Service Locator for Dart and Flutter projects with some additional goodies highly inspired by Splat. It can be used instead of InheritedWidget or Provider to access objects e.g. from your UI.
  get_it: ^5.0.1
  in_app_purchase: ^0.3.4+15
  # image_compressing
  flutter_image_compress: ^0.7.0
  # video_player
  # video_player: ^0.10.11+2
  cached_video_player: ^1.0.3
  common_utils: ^1.2.1
  # DateFormat
  timeago: ^2.0.28
  # Bloc Pattern
  flutter_bloc: ^6.1.0
  # RxDart
  rxdart: ^0.24.1
  # Simplify Equality Comparisons
  equatable: ^1.2.5
  flutter_swiper: ^1.1.6
  # ADs
  firebase_admob: ^0.10.2
  # native Ads
  flutter_native_admob: ^2.1.0+3
  # Firebase Auth - // Phone OTP
  firebase_auth: ^0.18.3
  # loading image from local -- new libraries
  photo_manager: ^0.5.8
  # Apple Sign in 2 - only iOS support
  apple_sign_in: ^0.1.0
  #encrypt
  encrypt: ^4.1.0
  #crop, compresss, resize image
  image_cropper: ^1.3.1
  # swipe list tile to show more options
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.1
  percent_indicator: 2.1.7+4
  # clipper for vip page
  flutter_custom_clippers: ^1.1.2
  # flutter_intro: ^0.7.0
  flutter_gradient_colors: ^1.0.0
  # flutter sqlite local database
  sqflite: ^1.3.2+1
  path: ^1.7.0
  # Duration picker
  flutter_picker: ^1.1.5
  video_trimmer: ^0.3.4
  video_compress: ^2.1.0
  visibility_detector: ^0.1.5
  #For Own Captch
  random_string: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # json_serializable: ^3.3.0
  # build_runner: ^1.9.0


flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/icons/
    - assets/icons/mainTab/
    - assets/icons/status/
    - assets/images/
    - assets/logos/
    - images/
    - images/mainTab/

  fonts:
    # - family: iconfont
    - family: appIconFonts
      fonts:
        # - asset: assets/fonts/alihomeiconfont.ttf
        - asset: assets/fonts/iconfont.ttf

flutter_intl:
  enabled: true
  class_name: G