name: moonblink
description: MoonBlink Universe's app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

 
  flutter_webrtc: ^0.2.8 #require to add code at android and ios
  cupertino_icons: ^0.1.2
  # State Management
  provider: ^4.0.4
  path_provider: ^1.6.11
  #Base Component
  device_info: ^0.4.2+4
  package_info: ^0.4.1
  #Base UI
  shimmer: ^1.1.1
  datetime_picker_formfield: ^1.0.0
  oktoast: ^2.3.2
  pull_to_refresh: ^1.6.0
  share: ^0.6.4+3
  flutter_local_notifications: ^1.4.4+1 # Android API 16+ (4.1+, the minimum version supported by Flutter). Uses the NotificationCompat APIs so it can be run older Android devices # iOS 8.0+ (the minimum version supported by Flutter). Supports the old and new iOS notification APIs (the User Notifications Framework introduced in iOS 10 but will use the UILocalNotification APIs for devices predating iOS 10)
  smooth_star_rating: ^1.1.1
  video_trimmer: ^0.2.6
  # fancy_bottom_navigation: ^0.3.2
  fancy_bottom_navigation:
    git:
      url: https://github.com/skquark/fancy_bottom_navigation.git
  # Data
  photo_view: ^0.9.2
  audioplayers: ^0.15.1
  flutter_audio_recorder: ^0.5.5
  dio: ^3.0.9
  shared_preferences: ^0.5.6+3
  socket_io_client: ^0.9.4
  scoped_model: ^1.0.1
  url_launcher: ^5.5.0
  #voice call
  agora_rtc_engine: ^1.0.13 #need to edit at android and ios
  permission_handler: ^5.0.1
  #camera
  camera: ^0.5.8+2 #need to edit at ios,andorid require 21 sdk version
  # local storage
  image_picker: ^0.6.7 #need to edit at android and ios
  localstorage: ^3.0.2+5
  story_view: ^0.12.3
  flutter_slidable: ^0.5.4
  vibration: ^1.4.0
  # azlistview: ^0.1.2 #no need to use this lib
  # lpinyin: ^1.0.9 #no need to use this lib
  # signIn helper
  google_sign_in: ^4.5.1 #complete for both
  flutter_facebook_login: ^3.0.0 #complete for both
  # FCM
  firebase_messaging: ^6.0.16
  # This is a simple Service Locator for Dart and Flutter projects with some additional goodies highly inspired by Splat. It can be used instead of InheritedWidget or Provider to access objects e.g. from your UI.
  get_it: ^4.0.2
  # in_app_purchase
  flutter_inapp_purchase: ^2.2.0
  # image_compressing
  flutter_image_compress: ^0.7.0
  # video_player
  video_player: ^0.10.11+2
  common_utils: ^1.2.1
  # DateFormat
  intl: ^0.16.1
  # Bloc Pattern
  flutter_bloc: ^6.0.1
  # RxDart
  rxdart: ^0.24.1
  # Simplify Equality Comparisons
  equatable: ^1.2.2
  flutter_swiper: ^1.1.6


  font_awesome_flutter: ^8.7.0 #The Font Awesome Icon pack available as set of Flutter Icons.
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  # json_serializable: ^3.3.0
  # build_runner: ^1.9.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - images/0.jpeg
    - images/1.jpeg
    - images/2.jpeg
    - images/3.jpeg
    - images/4.jpeg
    - images/5.jpeg


  fonts:
    # - family: iconfont
    - family: appIconFonts
      fonts:
        # - asset: assets/fonts/alihomeiconfont.ttf
        - asset: assets/fonts/iconfont.ttf

flutter_intl:
  enabled: true